# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/d857/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/d857/proprietary/etc/acdbdata/Bluetooth_cal.acdb:system/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/d857/proprietary/etc/acdbdata/General_cal.acdb:system/etc/acdbdata/General_cal.acdb \
    vendor/lge/d857/proprietary/etc/acdbdata/Global_cal.acdb:system/etc/acdbdata/Global_cal.acdb \
    vendor/lge/d857/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/d857/proprietary/etc/acdbdata/Hdmi_cal.acdb:system/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/d857/proprietary/etc/acdbdata/Headset_cal.acdb:system/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/d857/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/d857/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/lge/d857/proprietary/vendor/firmware/BCM4335_003.001.009.0105.0458_LGE_G3L_SPRINT_FM_ORC.hcd:system/vendor/firmware/BCM4335_003.001.009.0105.0458_LGE_G3L_SPRINT_FM_ORC.hcd \
    vendor/lge/d857/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/d857/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/d857/proprietary/lib/libvss_common_core.so:system/lib/libvss_common_core.so \
    vendor/lge/d857/proprietary/lib/libvss_nv_core.so:system/lib/libvss_nv_core.so \
    vendor/lge/d857/proprietary/lib/libvss_resim_core.so:system/lib/libvss_resim_core.so \
    vendor/lge/d857/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/lge/d857/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/lge/d857/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/lge/d857/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/lge/d857/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/lge/d857/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/lge/d857/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/lge/d857/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/lge/d857/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/lge/d857/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/lge/d857/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/lge/d857/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/lge/d857/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/lge/d857/proprietary/etc/firmware/fw_bcmdhd_mfg.bin:system/etc/firmware/fw_bcmdhd_mfg.bin \
    vendor/lge/d857/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal
